name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["feature"]
#projects: ["xenoncolt/Jellyflix_Android"]
assignees:
  - xenoncolt
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please select the type of feature request."
      options:
        - "New Feature"
        - "Improvement"
        - "Enhancement"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Describe the feature request"
      description: "A clear and concise description of what feature you are requesting. Include any specific details about the feature you would like to see added or improved."
      placeholder: "[something] is missing or [something] is not working as expected. I would like to see [something] added or improved."
    validations:
        required: true
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add any other context or screenshots about the feature request here."
    validations:
        required: false